/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

 #include "../../include/clap/include/clap/clap.h"
 #include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void* ClapGo_CreatePlugin(void* host, char* pluginID);
extern _Bool ClapGo_GetVersion(uint32_t* major, uint32_t* minor, uint32_t* patch);
extern char* ClapGo_GetPluginID(char* pluginID);
extern char* ClapGo_GetPluginName(char* pluginID);
extern char* ClapGo_GetPluginVendor(char* pluginID);
extern char* ClapGo_GetPluginVersion(char* pluginID);
extern char* ClapGo_GetPluginDescription(char* pluginID);
extern _Bool ClapGo_PluginInit(void* plugin);
extern void ClapGo_PluginDestroy(void* plugin);
extern _Bool ClapGo_PluginActivate(void* plugin, double sampleRate, uint32_t minFrames, uint32_t maxFrames);
extern void ClapGo_PluginDeactivate(void* plugin);
extern _Bool ClapGo_PluginStartProcessing(void* plugin);
extern void ClapGo_PluginStopProcessing(void* plugin);
extern void ClapGo_PluginReset(void* plugin);
extern int32_t ClapGo_PluginProcess(void* plugin, void* process);
extern void* ClapGo_PluginGetExtension(void* plugin, char* id);
extern void ClapGo_PluginOnMainThread(void* plugin);

#ifdef __cplusplus
}
#endif
